frontend:
  build: ./frontend
  ports:
    - "80:80"
  links:
    - backend
backend:
  command: "/bin/bash /src/run.sh"
  build: ./backend
  ports:
    - "8000:8000"
  volumes:
    - ./backend:/src
  environment:
    MONGO_HOST: mongo
    MONGO_PORT: 27017
  links:
    - mongo
mongo:
  image: mongo
